labels:
  language: ruby

version:
  semver:
    major: 0
    minor: 0

stages:
  trigger-github-pages-build:
    image: extensions/github-pages:stable
    token: estafette.secret(m1PLuxEdmZZ9RF2F.-ggNBrZVMZc6j4HExMQsKvrTpnzTpYYokYcNnOck7wzBYV76PqxCFcJ0VWsD8G5Z2_kSnbO_2pk=.-gkJMa1nTpU3gNrH2NA1Lf7Bkn7h9cJ-wf0wlfwAjVzjZx_0HU2lv4nw6QcIwsyqY2jG-Z0=)
    when:
      status == 'succeeded' &&
      branch == 'master'